conda_build_tool: rattler-build
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  osx_arm64: azure
